import EntityTypes from './EntityTypes.js'
import { Seasons } from './Calendar.js'

const CropData = {
  [EntityTypes.Lettuce]: {
    name: EntityTypes.Lettuce,
    seed: EntityTypes.LettuceSeed,
    seedPrice: 3,
    daysToGrow: 5,
    // inSeasonGrowthTime: 4,
    // outOfSeasonGrowthTime: 8,
    sellingPrice: 8,
    valuePerDay: 2,
    chanceOfSeedDrop: 0.05,
    maxSeedQuantity: 1,
    inSeason: Seasons.Rainy,
    minInSeasonYield: 1,
    maxInSeasonYield: 1,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: false,
    repeatDays: null,
    staminaRestored: 15
  },
  [EntityTypes.Strawberry]: {
    name: EntityTypes.Strawberry,
    seed: EntityTypes.StrawberrySeed,
    seedPrice: 4,
    daysToGrow: 4,
    // inSeasonGrowthTime: 4,
    // outOfSeasonGrowthTime: 6,
    sellingPrice: 8,
    valuePerDay: 2,
    chanceOfSeedDrop: 0.0,
    maxSeedQuantity: 1,
    inSeason: Seasons.Rainy,
    minInSeasonYield: 2,
    maxInSeasonYield: 3,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: true,
    repeatDays: 2,
    staminaRestored: 40
  },
  [EntityTypes.Eggplant]: {
    name: EntityTypes.Eggplant,
    seed: EntityTypes.EggplantSeed,
    seedPrice: 7,
    daysToGrow: 7,
    // inSeasonGrowthTime: 5,
    // outOfSeasonGrowthTime: 10,
    sellingPrice: 20,
    valuePerDay: 4,
    chanceOfSeedDrop: 0.10,
    maxSeedQuantity: 1,
    inSeason: Seasons.Cool,
    minInSeasonYield: 1,
    maxInSeasonYield: 1,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: false,
    repeatDays: null,
    staminaRestored: 40
  },
  [EntityTypes.Onion]: {
    name: EntityTypes.Onion,
    seed: EntityTypes.OnionSeed,
    seedPrice: 3,
    daysToGrow: 4,
    inSeasonGrowthTime: 4,
    outOfSeasonGrowthTime: 6,
    sellingPrice: 8,
    valuePerDay: 2,
    chanceOfSeedDrop: 0.05,
    maxSeedQuantity: 1,
    inSeason: Seasons.Cool,
    minInSeasonYield: 2,
    maxInSeasonYield: 4,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: false,
    repeatDays: null,
    staminaRestored: 15
  },
  [EntityTypes.Tomato]: {
    name: EntityTypes.Tomato,
    seed: EntityTypes.TomatoSeed,
    seedPrice: 3,
    daysToGrow: 4,
    // inSeasonGrowthTime: 4,
    // outOfSeasonGrowthTime: 6,
    sellingPrice: 6,
    valuePerDay: 2,
    chanceOfSeedDrop: 0.0,
    maxSeedQuantity: 1,
    inSeason: Seasons.Cool,
    minInSeasonYield: 2,
    maxInSeasonYield: 5,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 2,
    repeat: true,
    repeatDays: 3,
    staminaRestored: 55
  },
  [EntityTypes.Pepper]: {
    name: EntityTypes.Pepper,
    seed: EntityTypes.PepperSeed,
    seedPrice: 3,
    daysToGrow: 4,
    // inSeasonGrowthTime: 4,
    // outOfSeasonGrowthTime: 6,
    sellingPrice: 6,
    valuePerDay: 2,
    chanceOfSeedDrop: 0.0,
    maxSeedQuantity: 1,
    inSeason: Seasons.Hot,
    minInSeasonYield: 2,
    maxInSeasonYield: 5,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 2,
    repeat: true,
    repeatDays: 3,
    staminaRestored: 25
  },
  [EntityTypes.Carrot]: {
    name: EntityTypes.Carrot,
    seed: EntityTypes.CarrotSeed,
    seedPrice: 3,
    daysToGrow: 3,
    // inSeasonGrowthTime: 3,
    // outOfSeasonGrowthTime: 4,
    sellingPrice: 10,
    valuePerDay: 3,
    chanceOfSeedDrop: 0.05,
    maxSeedQuantity: 1,
    inSeason: Seasons.Hot,
    minInSeasonYield: 1,
    maxInSeasonYield: 3,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: false,
    repeatDays: null,
    staminaRestored: 25
  },
  [EntityTypes.Watermelon]: {
    name: EntityTypes.Watermelon,
    seed: EntityTypes.WatermelonSeed,
    seedPrice: 15,
    daysToGrow: 10,
    // inSeasonGrowthTime: 8,
    // outOfSeasonGrowthTime: 16,
    sellingPrice: 49,
    valuePerDay: 6,
    chanceOfSeedDrop: 0.025,
    maxSeedQuantity: 1,
    inSeason: Seasons.Hot,
    minInSeasonYield: 1,
    maxInSeasonYield: 1,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: false,
    repeatDays: null,
    staminaRestored: 60
  },
  [EntityTypes.Pumpkin]: {
    name: EntityTypes.Pumpkin,
    seed: EntityTypes.PumpkinSeed,
    seedPrice: 17,
    daysToGrow: 10,
    // inSeasonGrowthTime: 8,
    // outOfSeasonGrowthTime: 16,
    sellingPrice: 55,
    valuePerDay: 7,
    chanceOfSeedDrop: 0.025,
    maxSeedQuantity: 1,
    inSeason: Seasons.Rainy,
    minInSeasonYield: 1,
    maxInSeasonYield: 1,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: false,
    repeatDays: null,
    staminaRestored: 70
  },
  [EntityTypes.Corn]: {
    name: EntityTypes.Corn,
    seed: EntityTypes.CornSeed,
    seedPrice: 13,
    daysToGrow: 5,
    inSeasonGrowthTime: 4,
    outOfSeasonGrowthTime: 8,
    sellingPrice: 28,
    valuePerDay: 7,
    chanceOfSeedDrop: 0.0,
    maxSeedQuantity: 1,
    inSeason: Seasons.Hot,
    minInSeasonYield: 1,
    maxInSeasonYield: 1,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: true,
    repeatDays: 2,
    staminaRestored: 70
  },
  [EntityTypes.Potato]: {
    name: EntityTypes.Potato,
    seed: EntityTypes.PotatoSeed,
    seedPrice: 12,
    daysToGrow: 7,
    // inSeasonGrowthTime: 6,
    // outOfSeasonGrowthTime: 9,
    sellingPrice: 35,
    valuePerDay: 6,
    chanceOfSeedDrop: 0.15,
    maxSeedQuantity: 1,
    inSeason: Seasons.Cool,
    minInSeasonYield: 2,
    maxInSeasonYield: 4,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 1,
    repeat: false,
    repeatDays: null,
    staminaRestored: 25
  },
  [EntityTypes.Radish]: {
    name: EntityTypes.Radish,
    seed: EntityTypes.RadishSeed,
    seedPrice: 5,
    daysToGrow: 4,
    // inSeasonGrowthTime: 4,
    // outOfSeasonGrowthTime: 6,
    sellingPrice: 15,
    valuePerDay: 4,
    chanceOfSeedDrop: 0.05,
    maxSeedQuantity: 1,
    inSeason: Seasons.Rainy,
    minInSeasonYield: 2,
    maxInSeasonYield: 4,
    minOutOfSeasonYield: 1,
    maxOutOfSeasonYield: 2,
    repeat: false,
    repeatDays: null,
    staminaRestored: 15
  }
}

export const {
  Lettuce,
  Strawberry,
  Eggplant,
  Onion,
  Tomato,
  Pepper,
  Carrot,
  Watermelon,
  Pumpkin,
  Corn,
  Potato,
  Radish
} = CropData

export default CropData