const EntityTypes = {
  Apple: 'apple',
  AppleSeed: 'appleSeed',
  AppleTree: 'appleTree',
  AppleWood: 'appleWood',
  AxeCopper: 'axeCopper',
  AxeSteel: 'axeSteel',
  AxeTitanium: 'axeTitanium',
  Blacksmith: 'blacksmith',
  Butterfly: 'butterfly',
  Carpenter: 'carpenter',
  Carrot: 'carrot',
  CarrotSeed: 'carrotSeed',
  Catfish: 'catfish',
  Cherry: 'cherry',
  CherrySeed: 'cherrySeed',
  CherryTree: 'cherryTree',
  CherryWood: 'cherryWood',
  Corn: 'corn',
  CornSeed: 'cornSeed',
  Curator: 'curator',
  Daffodil: 'daffodil',
  Eggplant: 'eggplant',
  EggplantSeed: 'eggplantSeed',
  Fisherman: 'fisherman',
  FishingRodBamboo: 'fishingRodBamboo',
  FishingRodFiberglass: 'fishingRodFiberglass',
  FishingRodSteel: 'fishingRodSteel',
  Grandma: 'grandma',
  Guppy: 'guppy',
  Herring: 'herring',
  HoeWooden: 'hoeWooden',
  HoeSteel: 'hoeSteel',
  HoeCopper: 'hoeCopper',
  Lemon: 'lemon',
  LemonSeed: 'lemonSeed',
  LemonTree: 'lemonTree',
  LemonWood: 'lemonWood',
  Lettuce: 'lettuce',
  LettuceSeed: 'lettuceSeed',
  Lime: 'lime',
  LimeSeed: 'limeSeed',
  LimeTree: 'limeTree',
  LimeWood: 'limeWood',
  Lumberjack: 'lumberjack',
  MapleSeed: 'mapleSeed',
  MapleSyrup: 'mapleSyrup',
  MapleTree: 'mapleTree',
  MapleWood: 'mapleWood',
  Minnow: 'minnow',
  OakSeed: 'oakSeed',
  OakTree: 'oakTree',
  OakWood: 'oakWood',
  Onion: 'onion',
  OnionSeed: 'onionSeed',
  Orange: 'orange',
  OrangeSeed: 'orangeSeed',
  OrangeTree: 'orangeTree',
  OrangeWood: 'orangeWood',
  Pepper: 'pepper',
  PepperSeed: 'pepperSeed',
  PickaxeCopper: 'pickaxeCopper',
  PickaxeSteel: 'pickaxeSteel',
  PickaxeTitanium: 'pickaxeTitanium',
  Pike: 'pike',
  PineSeed: 'pineSeed',
  PineTree: 'pineTree',
  PineWood: 'pineWood',
  PlaqueFarming: 'plaqueFarming',
  PlaqueFishing: 'plaqueFishing',
  PlaqueForaging: 'plaqueForaging',
  PlaqueFurniture: 'plaqueFurniture',
  PlaqueSelling: 'plaqueSelling',
  Player1: 'player1',
  Player2: 'player2',
  Plum: 'plum',
  PlumSeed: 'plumSeed',
  PlumTree: 'plumTree',
  PlumWood: 'plumWood',
  PortraitMona: 'portraitMona',
  PortraitPearl: 'portraitPearl',
  PortraitRGB: 'portraitRGB',
  PortraitStarry: 'portraitStarry',
  PortraitWave: 'portraitWave',
  Potato: 'potato',
  PotatoSeed: 'potatoSeed',
  Pumpkin: 'pumpkin',
  PumpkinSeed: 'pumpkinSeed',
  Radish: 'radish',
  RadishSeed: 'radishSeed',
  Salmon: 'salmon',
  Sardine: 'sardine',
  Shopkeep: 'shopkeep',
  ShovelCopper: 'shovelCopper',
  ShovelSteel: 'shovelSteel',
  ShovelWooden: 'shovelWooden',
  StatueBust: 'statueBust',
  StatueFossil: 'statueFossil',
  StatueMoai: 'statueMoai',
  StatuePharaoh: 'statuePharaoh',
  Strawberry: 'strawberry',
  StrawberrySeed: 'strawberrySeed',
  Sunflower: 'sunflower',
  SunflowerSeed: 'sunflowerSeed',
  Tiffany: 'tiffany',
  Tomato: 'tomato',
  TomatoSeed: 'tomatoSeed',
  Truffel: 'truffel',
  Tulip: 'tulip',
  Tuna: 'tuna',
  Walleye: 'walleye',
  WateringCanCopper: 'wateringCanCopper',
  WateringCanSteel: 'wateringCanSteel',
  WateringCanWooden: 'wateringCanWooden',
  Watermelon: 'watermelon',
  WatermelonSeed: 'watermelonSeed',
  WildGarlic: 'wildGarlic',
  WildRose: 'wildRose'
}

export default EntityTypes
export const {
  Apple,
  AppleSeed,
  AppleTree,
  AppleWood,
  AxeCopper,
  AxeSteel,
  AxeTitanium,
  Blacksmith,
  Butterfly,
  Carpenter,
  Carrot,
  CarrotSeed,
  Catfish,
  Cherry,
  CherrySeed,
  CherryTree,
  CherryWood,
  Corn,
  CornSeed,
  Curator,
  Daffodil,
  Eggplant,
  EggplantSeed,
  Fisherman,
  FishingRodBamboo,
  FishingRodFiberglass,
  FishingRodSteel,
  Grandma,
  Guppy,
  Herring,
  HoeWooden,
  HoeSteel,
  HoeCopper,
  Lemon,
  LemonSeed,
  LemonTree,
  LemonWood,
  Lettuce,
  LettuceSeed,
  Lime,
  LimeSeed,
  LimeTree,
  LimeWood,
  Lumberjack,
  MapleSeed,
  MapleSyrup,
  MapleTree,
  Minnow,
  OakSeed,
  OakTree,
  OakWood,
  Onion,
  OnionSeed,
  Orange,
  OrangeSeed,
  OrangeTree,
  OrangeWood,
  Pepper,
  PepperSeed,
  PickaxeCopper,
  PickaxeSteel,
  PickaxeTitanium,
  Pike,
  PineSeed,
  PineTree,
  PineWood,
  PlaqueFarming,
  PlaqueFishing,
  PlaqueForaging,
  PlaqueFurniture,
  PlaqueSelling,
  Player1,
  Player2,
  Plum,
  PlumSeed,
  PlumTree,
  PlumWood,
  PortraitMona,
  PortraitPearl,
  PortraitRGB,
  PortraitStarry,
  PortraitWave,
  Potato,
  PotatoSeed,
  Pumpkin,
  PumpkinSeed,
  Radish,
  RadishSeed,
  Salmon,
  Sardine,
  Shopkeep,
  ShovelCopper,
  ShovelSteel,
  ShovelWooden,
  StatueBust,
  StatueFossil,
  StatueMoai,
  StatuePharaoh,
  Strawberry,
  StrawberrySeed,
  Sunflower,
  SunflowerSeed,
  Tiffany,
  Tomato,
  TomatoSeed,
  Truffel,
  Tulip,
  Tuna,
  Walleye,
  WateringCanCopper,
  WateringCanSteel,
  WateringCanWooden,
  Watermelon,
  WatermelonSeed,
  WildGarlic,
  WildRose
} =  EntityTypes