const EntityTypes = {
  Apple: 'apple',
  AppleTree: 'appleTree',
  Carrot: 'carrot',
  Catfish: 'catfish',
  Cherry: 'cherry',
  CherryTree: 'cherryTree',
  Corn: 'corn',
  Daffodil: 'daffodil',
  Eggplant: 'eggplant',
  Guppy: 'guppy',
  Herring: 'herring',
  Lemon: 'lemon',
  LemonTree: 'lemonTree',
  Lettuce: 'lettuce',
  Lime: 'lime',
  LimeTree: 'limeTree',
  MapleTree: 'mapleTree',
  Minnow: 'minnow',
  OakTree: 'oakTree',
  Onion: 'onion',
  Orange: 'orange',
  OrangeTree: 'orangeTree',
  Pepper: 'pepper',
  Pike: 'pike',
  PineTree: 'pineTree',
  Player1: 'player1',
  Player2: 'player2',
  Plum: 'plum',
  Potato: 'potato',
  Pumpkin: 'pumpkin',
  Radish: 'radish',
  Salmon: 'salmon',
  Sardine: 'sardine',
  Strawberry: 'strawberry',
  Sunflower: 'sunflower',
  Tomato: 'tomato',
  Truffel: 'truffel',
  Tulip: 'tulip',
  Tuna: 'tuna',
  Walleye: 'walleye',
  Watermelon: 'watermelon',
  WildGarlic: 'wildGarlic',
  WildRose: 'wildRose'
}

export default EntityTypes
export const {
  Apple,
  AppleTree,
  Carrot,
  Catfish,
  Cherry,
  CherryTree,
  Corn,
  Daffodil,
  Eggplant,
  Guppy,
  Herring,
  Lemon,
  LemonTree,
  Lettuce,
  Lime,
  LimeTree,
  MapleTree,
  Minnow,
  OakTree,
  Onion,
  Orange,
  OrangeTree,
  Pepper,
  Pike,
  PineTree,
  Player1,
  Player2,
  Plum,
  Potato,
  Pumpkin,
  Radish,
  Salmon,
  Sardine,
  Strawberry,
  Sunflower,
  Tomato,
  Truffel,
  Tulip,
  Tuna,
  Walleye,
  Watermelon,
  WildGarlic,
  WildRose
} =  EntityTypes