const Images = {
  BasePlayer: '../../img/BasePlayer - Copy.png',
  Curator: '../../img/Curator.png',
  ForageableItems: '../../img/Forage.png',
  Museum: '../../img/Museum.png',
  NPCs: '../../img/NPCs.png',
  Plaques: '../../img/Plaques.png',
  Portraits: '../../img/Portraits.png',
  ShortCrops: '../../img/ShortCrops.png',
  Statues: '../../img/Statues.png',
  TallCrops: '../../img/TallCrops.png',
  TileSet: '../../img/tileset.png',
  TitleBackground: '../../img/TitleScreen.png',
  Tools: '../../img/Tools.png',
  UISprites: '../../img/UISprites.png',
  WildlifeSprites: '../../img/Wildlife.png',
  RainSprite: '../../img/rain.png',
  SnowSprite: '../../img/snow.png',
}

export default Images
export const {
  BasePlayer,
  Curator,
  ForageableItems,
  Museum,
  NPCs,
  Plaques,
  Portraits,
  ShortCrops,
  Statues,
  TallCrops,
  TileSet,
  TitleBackground,
  Tools,
  UISprites,
  WildlifeSprites,
  RainSprite,
  SnowSprite,
} =  Images