const Sounds = {
  BackgroundMusic: '../../sounds/cozyCropsMainBackgroundMusic.mp3',
  RainSound: '../../sounds/rain.mp3',
  WindSound: '../../sounds/wind.mp3',
  BackgroundBirds: '../../sounds/birds.mp3',
  BackgroundWaterfall: '../../sounds/waterfall.mp3',
  BackgroundSeashore: '../../sounds/seashore.mp3',
  waterGroundSound: '../../sounds/waterGround.mp3',
  tillGroundSound: '../../sounds/tillGround.mp3',
  openDoorSound: '../../sounds/openDoor.mp3',
  harvestCropSound: '../../sounds/harvestCrop.mp3',
  plantSeedSound: '../../sounds/plantSeed.mp3',
  stepSound1: '../../sounds/footStep1.wav',
  stepSound2: '../../sounds/footStep2.wav',
  stepSound3: '../../sounds/footStep3.wav',
  stepSound4: '../../sounds/footStep4.wav',
}

export default Sounds
export const {
  BackgroundMusic,
  RainSound,
  WindSound,
  BackgroundBirds,
  BackgroundWaterfall,
  BackgroundSeashore,
  waterGroundSound,
  tillGroundSound,
  openDoorSound,
  harvestCropSound,
  plantSeedSound,
  stepSound1,
  stepSound2,
  stepSound3,
  stepSound4,    
 } =  Sounds